safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: 管理者园地
host: localhost
desc: 彼得·德鲁克：管理是一种实践，其本质不在于“知”而在于“行”；其验证不在于逻辑，而在于成果；其唯一权威就是成就。

custom:
    category:
        default: Default Category
        organization: Organization Category
        development: Development Category
        marketing: Marketing Category
        requirement: Requirement Category
        technique: Technique Category
        enable: Enable Category
        human: Human Category
    categories:
      - name:  default
        title: Default Category

      - name:  organization
        title: Organization Category   
        
      - name:  development
        title: Development Category        

      - name:  marketing
        title: Marketing Category

      - name:  requirement
        title: Requirement Category
      
      - name:  technique
        title: Technique Category
        
      - name:  enable
        title: Enable Category      
        
      - name:  human
        title: Human Category   

    scrollingLoadCount: 0                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: Hewin Consultant
        email: mail@hewinsz.com
        disqus: your-disqus-short-name              # Disqus缩略标识
        gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
        github: cnhewin                             # GitHub账号
        gravatar: a1d858b3e21a066ac6a41eeae41457c2  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
